name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Setup PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.12' # Sesuaikan dengan versi PHP Anda
        extensions: mbstring, bcmath, intl, pdo_mysql, pdo_sqlite
        ini-values: post_max_size=256M, upload_max_filesize=256M

    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Copy .env.testing for testing environment
    - name: Set up Testing Environment
      run: cp .env.example .env

    # Install Dependencies
    - name: Install Dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    # Generate Application Key
    - name: Generate Application Key
      run: php artisan key:generate

    # Set Directory Permissions
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Create SQLite Database
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Run Laravel Migrations
    - name: Run Migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    # Execute Tests
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
